FROM node:18-alpine

WORKDIR /app

# Copy application files
COPY . .

# Install dependencies
RUN yarn install

# Expose the port
EXPOSE 3001

# Start the development server
CMD ["yarn", "dev", "-p", "3001"]
