version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prebuild
    container_name: multilingual-chat-frontend
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://148.113.181.101:8000
    restart: unless-stopped
    networks:
      - frontend-network
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next

networks:
  frontend-network:
    name: frontend-network
    driver: bridge
