version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: multilingual-chat-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://148.113.181.101:8000
    restart: unless-stopped
    networks:
      - frontend-network
    # Uncomment the following lines if you need to mount volumes for development
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    #   - /app/.next
    # Resource limits to prevent build issues
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

networks:
  frontend-network:
    name: frontend-network
    driver: bridge
